[package]
name = "k2so"
version = "2.0.0"
authors = ["Jan Schulte <hello@unexpected-co.de>"]
license = "MIT"
description = "Deployment droid"
[dependencies]
clap = "~2.19.0"
toml = "0.2"
rustc-serialize = "0.3"